import spamwatch

from Konf import *
TOKEN = TOKEN
OWNER_ID = int(OWNER_ID)
JOIN_LOGGER = JOIN_LOGGER
OWNER_USERNAME = OWNER_USERNAME
ALLOW_CHATS = ALLOW_CHATS
SUDO_USERS = set(int(x) for x in SUDO_USERS or [])
DEV_USERS = set(int(x) for x in DEV_USERS or [])
EVENT_LOGS = EVENT_LOGS
API_ID = API_ID
API_HASH = API_HASH
DB_URI = SQLALCHEMY_DATABASE_URI
LOAD = LOAD
NO_LOAD = NO_LOAD
DEL_CMDS = DEL_CMDS
STRICT_GBAN = STRICT_GBAN
WORKERS = WORKERS
BAN_STICKER = BAN_STICKER
ALLOW_EXCL = ALLOW_EXCL
CASH_API_KEY = CASH_API_KEY
TIME_API_KEY = TIME_API_KEY
SUPPORT_CHAT = SUPPORT_CHAT
SPAMWATCH_SUPPORT_CHAT = SPAMWATCH_SUPPORT_CHAT
SPAMWATCH_API = SPAMWATCH_API
INFOPIC = INFOPIC
WEATHER_API = WEATHER_API
SUDO_USERS.add(OWNER_ID)
DEV_USERS.add(OWNER_ID)
sw = spamwatch.Client(SPAMWATCH_API)