import spamwatch

from Konf import Development as Config
TOKEN = Config.TOKEN
OWNER_ID = int(Config.OWNER_ID)
JOIN_LOGGER = Config.JOIN_LOGGER
OWNER_USERNAME = Config.OWNER_USERNAME
ALLOW_CHATS = Config.ALLOW_CHATS
SUDO_USERS = set(int(x) for x in Config.SUDO_USERS or [])
DEV_USERS = set(int(x) for x in Config.DEV_USERS or [])
EVENT_LOGS = Config.EVENT_LOGS
API_ID = Config.API_ID
API_HASH = Config.API_HASH
DB_URI = Config.SQLALCHEMY_DATABASE_URI
LOAD = Config.LOAD
NO_LOAD = Config.NO_LOAD
DEL_CMDS = Config.DEL_CMDS
STRICT_GBAN = Config.STRICT_GBAN
WORKERS = Config.WORKERS
BAN_STICKER = Config.BAN_STICKER
ALLOW_EXCL = Config.ALLOW_EXCL
CASH_API_KEY = Config.CASH_API_KEY
TIME_API_KEY = Config.TIME_API_KEY
SUPPORT_CHAT = Config.SUPPORT_CHAT
SPAMWATCH_SUPPORT_CHAT = Config.SPAMWATCH_SUPPORT_CHAT
SPAMWATCH_API = Config.SPAMWATCH_API
INFOPIC = Config.INFOPIC
WEATHER_API = Config.WEATHER_API
SUDO_USERS.add(OWNER_ID)
DEV_USERS.add(OWNER_ID)
sw = spamwatch.Client(SPAMWATCH_API)